// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: todoList_proto.proto

package todo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Todo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	ToDo     string `protobuf:"bytes,2,opt,name=toDo,proto3" json:"toDo,omitempty"`
}

func (x *Todo) Reset() {
	*x = Todo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoList_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todoList_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_todoList_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *Todo) GetToDo() string {
	if x != nil {
		return x.ToDo
	}
	return ""
}

type TodoID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TodoID) Reset() {
	*x = TodoID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoList_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoID) ProtoMessage() {}

func (x *TodoID) ProtoReflect() protoreflect.Message {
	mi := &file_todoList_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoID.ProtoReflect.Descriptor instead.
func (*TodoID) Descriptor() ([]byte, []int) {
	return file_todoList_proto_proto_rawDescGZIP(), []int{1}
}

func (x *TodoID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_todoList_proto_proto protoreflect.FileDescriptor

var file_todoList_proto_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x22, 0x36, 0x0a, 0x04,
	0x54, 0x6f, 0x64, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x44, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x6f, 0x44, 0x6f, 0x22, 0x1e, 0x0a, 0x06, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x32, 0x33, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x27, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x0a, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x1a, 0x0c, 0x2e, 0x74, 0x6f,
	0x64, 0x6f, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x44, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x74, 0x6f,
	0x64, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_todoList_proto_proto_rawDescOnce sync.Once
	file_todoList_proto_proto_rawDescData = file_todoList_proto_proto_rawDesc
)

func file_todoList_proto_proto_rawDescGZIP() []byte {
	file_todoList_proto_proto_rawDescOnce.Do(func() {
		file_todoList_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_todoList_proto_proto_rawDescData)
	})
	return file_todoList_proto_proto_rawDescData
}

var file_todoList_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_todoList_proto_proto_goTypes = []interface{}{
	(*Todo)(nil),   // 0: todo.Todo
	(*TodoID)(nil), // 1: todo.TodoID
}
var file_todoList_proto_proto_depIdxs = []int32{
	0, // 0: todo.TodoList.addTodoList:input_type -> todo.Todo
	1, // 1: todo.TodoList.addTodoList:output_type -> todo.TodoID
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_todoList_proto_proto_init() }
func file_todoList_proto_proto_init() {
	if File_todoList_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todoList_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Todo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoList_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todoList_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todoList_proto_proto_goTypes,
		DependencyIndexes: file_todoList_proto_proto_depIdxs,
		MessageInfos:      file_todoList_proto_proto_msgTypes,
	}.Build()
	File_todoList_proto_proto = out.File
	file_todoList_proto_proto_rawDesc = nil
	file_todoList_proto_proto_goTypes = nil
	file_todoList_proto_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TodoListClient is the client API for TodoList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoListClient interface {
	AddTodoList(ctx context.Context, in *Todo, opts ...grpc.CallOption) (*TodoID, error)
}

type todoListClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoListClient(cc grpc.ClientConnInterface) TodoListClient {
	return &todoListClient{cc}
}

func (c *todoListClient) AddTodoList(ctx context.Context, in *Todo, opts ...grpc.CallOption) (*TodoID, error) {
	out := new(TodoID)
	err := c.cc.Invoke(ctx, "/todo.TodoList/addTodoList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoListServer is the server API for TodoList service.
type TodoListServer interface {
	AddTodoList(context.Context, *Todo) (*TodoID, error)
}

// UnimplementedTodoListServer can be embedded to have forward compatible implementations.
type UnimplementedTodoListServer struct {
}

func (*UnimplementedTodoListServer) AddTodoList(context.Context, *Todo) (*TodoID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTodoList not implemented")
}

func RegisterTodoListServer(s *grpc.Server, srv TodoListServer) {
	s.RegisterService(&_TodoList_serviceDesc, srv)
}

func _TodoList_AddTodoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Todo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServer).AddTodoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoList/AddTodoList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServer).AddTodoList(ctx, req.(*Todo))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.TodoList",
	HandlerType: (*TodoListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addTodoList",
			Handler:    _TodoList_AddTodoList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todoList_proto.proto",
}
